<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@if(@$name){{ $name }} - @endif{{ $site['title'] }}</title>
    <link rel="stylesheet" type="text/css" href="/styles/bundle.css">
  </head>
  <body class="view-{{ $view }}">
    <main class="container">
      <div class="pure-g">
        <div class="pure-u-1-6"></div>
        <div class="pure-u-5-6">
          <h2>
            <a href="{{ $site['link'] }}">
              {{ $site['title'] }}
            </a>
          </h2>

          @if(@$name)<h1>{{ $name }}</h1>@endif
        </div>
      </div>

      @yield('content')

      <footer>
        Generated by <a href="https://11ty.dev">eleventy</a> at <time>XXX</time>.
      </footer>
    </main>
    <script src="/scripts/bundle.js"></script>
    <script src="//localhost:35729/livereload.js"></script>
  </body>
</html>
